import = ["/Users/eriko/.config/alacritty/colorscheme/solarized.toml"]

[shell]
program = "/opt/homebrew/bin/fish"

[colors.cursor]
cursor = "#839496"

[font]
size = 25.0

[font.bold]
family = "PlemolJP Console NF"
style = "bold"

[font.bold_italic]
family = "PlemolJP Console NF"
style = "italic"

[font.italic]
family = "PlemolJP Console NF"
style = "italic"

[font.normal]
family = "PlemolJP Console NF"
style = "Regular"

[window]
decorations = "full"
opacity = 0.7
