import = ["/Users/eriko/.config/alacritty/colorscheme/solarized.toml"]

[shell]
program = "/opt/homebrew/bin/fish"

[colors.cursor]
cursor = "#839496"

[font]
size = 24

[font.normal]
family = "PlemolJPConsoleNF Nerd Font"
style = "Light"

[font.bold]
style = "Light"

[font.bold_italic]
style = "Light"

[font.italic]
style = "Light Italic"

[font.offset]
x = 1
y = 0

[window]
decorations = "full"
opacity = 0.8
 
[terminal]
osc52 = "CopyPaste"
