require("config.options")
require("config.autocmds")
require("config.lazy")
require("config.key-menu")
require("config.keymaps")
require("config.lsp")
require("config.diagnostic-ui")
vim.cmd([[colorscheme solarized]])
