return {
  {
    -- This plugin is the pure lua replacement for github/copilot.vim.
    -- "zbirenbaum/copilot.lua",
    -- event = "InsertEnter",
    -- opts = function()
    --   require("copilot.api").status = require("copilot.status")
    -- end,
  },
  -- {
  --   "CopilotC-Nvim/CopilotChat.nvim",
  --   build = "make tiktoken",
  --   opts = {
  --     language = "Japanese",
  --   },
  -- },
  {

    -- "yetone/avante.nvim",
    -- -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
    -- -- ⚠️ must add this setting! ! !
    -- build = vim.fn.has("win32") ~= 0 and "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false"
    --   or "make",
    -- event = "VeryLazy",
    -- version = false, -- Never set this value to "*"! Never!
    -- ---@module 'avante'
    -- ---@type avante.Config
    -- opts = {
    --   -- add any opts here
    --   -- this file can contain specific instructions for your project
    --   -- instructions_file = "avante.md",
    --   -- for example
    --   provider = "copilot",
    --   providers = {
    --     copilot = {
    --       endpoint = "https://api.githubcopilot.com",
    --       model = "claude-opus-4-5-20251101",
    --       timeout = 30000, -- Timeout in milliseconds
    --       extra_request_body = {
    --         temperature = 0.75,
    --         max_tokens = 20480,
    --       },
    --     },
    --   },
    -- },
    -- dependencies = {
    --   "nvim-mini/mini.pick", -- for file_selector provider mini.pick
    --   -- "hrsh7th/nvim-cmp", -- autocompletion for avante commands and mentions
    --   -- "ibhagwan/fzf-lua", -- for file_selector provider fzf
    --   {
    --     "zbirenbaum/copilot.lua",
    --     opts = function()
    --       require("copilot.api").status = require("copilot.status")
    --     end,
    --   },
    --   {
    --     -- support for image pasting
    --     "HakonHarnes/img-clip.nvim",
    --     event = "VeryLazy",
    --     opts = {
    --       -- recommended settings
    --       default = {
    --         embed_image_as_base64 = false,
    --         prompt_for_file_name = false,
    --         drag_and_drop = {
    --           insert_mode = true,
    --         },
    --         -- required for Windows users
    --         use_absolute_path = true,
    --       },
    --     },
    --   },
    -- },
  },
  {
    -- copilot cliがofferboxのリポジトリでdisabledなので使えない、、
    -- "folke/sidekick.nvim",
    -- opts = {
    --   -- add any options here
    -- },
    -- keys = {
    --   {
    --     "<tab>",
    --     function()
    --       -- if there is a next edit, jump to it, otherwise apply it if any
    --       if not require("sidekick").nes_jump_or_apply() then
    --         return "<Tab>" -- fallback to normal tab
    --       end
    --     end,
    --     expr = true,
    --     desc = "Goto/Apply Next Edit Suggestion",
    --   },
    --   {
    --     "<c-.>",
    --     function()
    --       require("sidekick.cli").toggle()
    --     end,
    --     desc = "Sidekick Toggle",
    --     mode = { "n", "t", "i", "x" },
    --   },
    --   {
    --     "<leader>aa",
    --     function()
    --       require("sidekick.cli").toggle()
    --     end,
    --     desc = "Sidekick Toggle CLI",
    --   },
    --   {
    --     "<leader>as",
    --     function()
    --       require("sidekick.cli").select()
    --     end,
    --     -- Or to select only installed tools:
    --     -- require("sidekick.cli").select({ filter = { installed = true } })
    --     desc = "Select CLI",
    --   },
    --   {
    --     "<leader>ad",
    --     function()
    --       require("sidekick.cli").close()
    --     end,
    --     desc = "Detach a CLI Session",
    --   },
    --   {
    --     "<leader>at",
    --     function()
    --       require("sidekick.cli").send({ msg = "{this}" })
    --     end,
    --     mode = { "x", "n" },
    --     desc = "Send This",
    --   },
    --   {
    --     "<leader>af",
    --     function()
    --       require("sidekick.cli").send({ msg = "{file}" })
    --     end,
    --     desc = "Send File",
    --   },
    --   {
    --     "<leader>av",
    --     function()
    --       require("sidekick.cli").send({ msg = "{selection}" })
    --     end,
    --     mode = { "x" },
    --     desc = "Send Visual Selection",
    --   },
    --   {
    --     "<leader>ap",
    --     function()
    --       require("sidekick.cli").prompt()
    --     end,
    --     mode = { "n", "x" },
    --     desc = "Sidekick Select Prompt",
    --   },
    --   -- Example of a keybinding to open Claude directly
    --   {
    --     "<leader>ac",
    --     function()
    --       require("sidekick.cli").toggle({ name = "claude", focus = true })
    --     end,
    --     desc = "Sidekick Toggle Claude",
    --   },
    -- },
  },
}
