-- require("dap").setup()
--
-- vim.api.nvim_set_keymap("n", "<F5>", "<Cmd>lua require('dap').toggle_breakpoint()", { silent = true })
-- vim.api.nvim_set_keymap('n', '<F6>', ':DapStepInto<CR>', { silent = true })
-- vim.api.nvim_set_keymap('n', '<F10>', ':DapStepOver<CR>', { silent = true })
-- vim.api.nvim_set_keymap('n', '<F12>', ':DapStepOut<CR>', { silent = true })
-- vim.api.nvim_set_keymap('n', '<leader>db', ':DapToggleBreakpoint<CR>', { silent = true })
-- vim.api.nvim_set_keymap('n', '<leader>dr', ':lua require("dap").repl.open()<CR>', { silent = true })
-- vim.api.nvim_set_keymap('n', '<leader>dl', ':lua require("dap").run_last()<CR>', { silent = true })
