-- press <Tab> to expand or jump in a snippet. These can also be mapped separately
-- via <Plug>luasnip-expand-snippet and <Plug>luasnip-jump-next.
-- local ls = require("luasnip").setup({})
-- vim.keymap.set({ "i" }, "<C-K>", function()
--   ls.expand()
-- end, { silent = true })
-- vim.keymap.set({ "i", "s" }, "<C-L>", function()
--   ls.jump(1)
-- end, { silent = true })
-- vim.keymap.set({ "i", "s" }, "<C-J>", function()
--   ls.jump(-1)
-- end, { silent = true })
--
-- vim.keymap.set({ "i", "s" }, "<C-E>", function()
--   if ls.choice_active() then
--     ls.change_choice(1)
--   end
-- end, { silent = true })
