session_name: dev-sample
windows:
  - window_name: public_html
    panes:
      - z public_html |clear
  - window_name: logs
    panes:
      - z logs |clear
  - window_name: DBeaver
    panes:
      - cd ~/Library/DBeaverData/workspace6/General/Scripts |clear
  - window_name: neorg_notes
    panes:
      - z neorg_notes |clear
  - window_name: nvim
    layout: tiled
    panes:
        - z nvim |clear
  - window_name: tmux
    panes:
        - z tmux |clear
  - window_name: fish
    panes:
        - z fish |clear
  - window_name: wezterm
    panes:
        - z wezterm |clear
