session_name: dev-sample
windows:
  - window_name: public_html
    panes:
      - z public_html |clear
  - window_name: public_html
    panes:
      - z public_html |clear
  - window_name: weekly
    panes:
      - z weekly |clear
